export const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGN_UP_SUCCESS : "SIGN_UP_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    USER_ADDITION_SUCCESS: "USER_ADDITION_SUCCESS",
    USER_BLOCKDATA_ADDITION: "USER_BLOCKDATA_ADDITION",
    BRANCH_ADDITION_SUCCESS:"BRANCH_ADDITION_SUCCESS",
    USER_PROFILE_FETCH:"USER_PROFILE_FETCH"
};