export const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    SIGN_UP_SUCCESS : "SIGN_UP_SUCCESS",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    USER_ADDITION: "USER_ADDITION",
    USER_BLOCKDATA_ADDITION: "USER_BLOCKDATA_ADDITION"
};